

service: hubspot-api #

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128

functions:
  contact:
    handler: handler.hello
    events:
      - http:
          path: /
          method: ANY
          cors: true
